version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: dynamodb,s3,lambda
      DEFAULT_REGION: ${AWS_REGION}
      DATA_DIR: /var/lib/localstack/data
      TMPDIR: /var/tmp/localstack
      PORT_WEB_UI: 8080
    ports:
      - "4566:4566"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health || exit 1"]
      interval: 5s
      retries: 20

  pdf_service:
    build: ./pdf_service
    env_file:
      - ./.env
    volumes:
      - ./pdf_service/uploads:/app/uploads
      - ./pdf_service/pdf_metadata.db:/app/pdf_metadata.db
    ports:
      - "${PDF_SERVICE_PORT}:8000"
    depends_on:
      - localstack

  rag_module:
    build: ./rag_module
    env_file:
      - ./.env
    ports:
      - "${RAG_SERVICE_PORT}:8001"
    depends_on:
      - metrics_stub

  aws_service:
    build: ./aws_service
    env_file:
      - ./.env
    ports:
      - "${AWS_SERVICE_PORT}:8002"
    depends_on:
      - localstack
      - rag_module

  metrics_stub:
    build: ./metrics_lambda
    env_file:
      - ./.env
    ports:
      - "${METRICS_STUB_PORT}:9000"
    depends_on:
      - localstack
